### ISSUE TITLE
README clarification

### ISSUE THREAD

**Issue by carlcorder** [devinsmith/rca-cambio-linux#1]
In the README you mention:

> By default the RCA Cambio runs in portrait mode, but before booting you'll want to add video=efifb fbcon=rotate:1 to your kernel command line.

I've read some of the documentation here: http://linuxiumcomau.blogspot.com/2017/06/customizing-ubuntu-isos-documentation.html

But it's not clear to me if I should remove the default kernel boot parameters (in my case):

`isorespin.sh -i elementaryos-0.4.1-stable.20180214.iso -g "" -g "video=efifb fbcon=rotate:1" --atom`

or simply add the parameters you mention:

`isorespin.sh -i elementaryos-0.4.1-stable.20180214.iso -g "video=efifb fbcon=rotate:1" --atom`

**Comment by devinsmith** [comment]
Sorry for the delay, probably the last one: 
isorespin.sh -i elementaryos-0.4.1-stable.20180214.iso -g "video=efifb fbcon=rotate:1" --atom

I'm not sure why you would pass -g and an empty string.

**Comment by carlcorder** [comment]
I think the first `-g ""` clears the boot parameters? Not sure either. At any rate, thanks for your response!
