### ISSUE TITLE
bash:ATTRS{name}==silead_ts,: command not found

### ISSUE THREAD

**Issue by ungaungaungaunga** [devinsmith/rca-cambio-linux#13]
Fedora 35.

**Comment by ungaungaungaunga** [comment]
When running python: "invalid syntax"

**Comment by devinsmith** [comment]
I think this is not a command that you run in Python or bash directly, it's a udev rule.

**Comment by ungaungaungaunga** [comment]
exactly why I had to change the instructions, the way you phrased it made it sound like a "Oh, throw it in the terminal" instead of running Nano and dropping the file in where it should be. The command above it to "make the file" doesn't work. I have given an alternative using Nano and manually pasting the command in. I still don't know if pip or ATTRS need to be installed, but, in my case it didn't hurt. 

Not everyone knows Linux, so that's why it needs rephrasing, I am not great with it either, but, I think I broke  it down enough to be easy to follow .
