### ISSUE TITLE
This page isn't saying how much of its hardware you got to work

### ISSUE THREAD

**Issue by divVerent** [devinsmith/rca-cambio-linux#2]
Hi,

not sure where to ask this question - but I'm considering buying this device and am wondering how much of its hardware you got to run, in particular:

- touchscreen
- audio
- bluetooth
- the keyboard that comes with it

Can you tell how much of this works out of the box and how much of this needed configuration but eventually worked?

Thanks!

**Comment by deadaluspark** [comment]
Hi, I did not make this page but I have used this device with Linux, so I can say that audio and keyboard work fine on install.  However, Bluetooth is finnicky, although I've gotten it to work a handful of times (not sure how) and the touchscreen is a no-go.

Not sure how much work would be involved to make those components work better.

**Comment by RayFoulk** [comment]
ditto deadaluspark's advice.  audio works, but the gain value is backwards for the headphones for me (lower value = louder).  touchscreen requires a custom kernel patch as the mainline kernel hasn't picked up the necessary parameters yet.

**Comment by devinsmith** [comment]
Audio, wifi and keyboard work. I don't use Bluetooth. The device can get a little finicky and the  keyboard sometimes goes through an interrupt storm. The only way to resolve that is to detach the keyboard and reattach it again.

**Comment by slobo** [comment]
@RayFoulk, do you happen to have any pointers on where to find the touchscreen patch? My google-fu is failing me...

Thanks!

**Comment by rbeede** [comment]
Has anyone got this to work on a W101SA23T1 ?

I tried Debian, and it installed, but at boot the display just goes blank and remains that way. Seems to be video driver related?

I did the respin on Ubuntu 18.04.5 and could get the USB installer to boot to grub, but after selecting to start the install the screen just stays blank again like with Debian.

**Comment by adrcunha** [comment]
I believe that my latest series of updates addressed all the concerns in this issue and thus it can be closed.

**Comment by ohjhas** [comment]
i managed to get all working except wifi crashes and rotation

wifi crashes sometimes and you need to restart chip service

the rotation is inverted and i couldn't get it fixed, now i am on win10 22h2 32 bit and so far it works well with a debloat and telemetry and some services disabled

**Comment by adrcunha** [comment]
You did not mention which distro(s) you tried, but it seems to be Ubuntu 20 because both issues (WiFi and rotation) are mentioned in the "Known issues" section. If Windows 10 is working fine for you, great, otherwise I'd suggest giving Ubuntu 22 a try, it's been working great for me.

**Comment by ohjhas** [comment]
> You did not mention which distro(s) you tried, but it seems to be Ubuntu 20 because both issues (WiFi and rotation) are mentioned in the "Known issues" section. If Windows 10 is working fine for you, great, otherwise I'd suggest giving Ubuntu 22 a try, it's been working great for me.

i did use Ubuntu 22.04.4 LTS, if rotation was working, i would use it

**Comment by ohjhas** [comment]
> You did not mention which distro(s) you tried, but it seems to be Ubuntu 20 because both issues (WiFi and rotation) are mentioned in the "Known issues" section. If Windows 10 is working fine for you, great, otherwise I'd suggest giving Ubuntu 22 a try, it's been working great for me.

also, i opened a issue on this repo with that bug

**Comment by ohjhas** [comment]
> You did not mention which distro(s) you tried, but it seems to be Ubuntu 20 because both issues (WiFi and rotation) are mentioned in the "Known issues" section. If Windows 10 is working fine for you, great, otherwise I'd suggest giving Ubuntu 22 a try, it's been working great for me.

and, how did you fix the rotation issue?

answer on #15
