### ISSUE TITLE
Working on model W101SA23T1  ?

### ISSUE THREAD

**Issue by rbeede** [devinsmith/rca-cambio-linux#3]
Has anyone got this to work on a W101SA23T1 ?

I tried Debian, and it installed, but at boot the display just goes blank and remains that way. Seems to be video driver related?

I did the respin on Ubuntu 18.04.5 and could get the USB installer to boot to grub, but after selecting to start the install the screen just stays blank again like with Debian.

I am trying VoidLinux with the image at https://alpha.de.repo.voidlinux.org/live/current/void-live-i686-20191109.iso  even though it is from 2019 it appears.  Right now it is sitting at Starting udev and waiting for devices to settle...

**Comment by rbeede** [comment]
No luck with VoidLinux. I've also tried

- firmware-10.7.0-amd64-i386-netinst.iso
- void-live-i686-20191109.iso
- linuxium-atom-ubuntu-18.04.5-desktop-amd64.iso
- Fedora-Xfce-Live-x86_64-33-1.2.iso

**Comment by rbeede** [comment]
So I let the USB (with the dd image Fedora-Xfce-Live-x86_64-33-1.2.iso) just sit overnight at the blank screen after selecting it to boot.  This morning I came in, and the Live ISO USB had booted to a usable GUI. I am running the installer right now.

**Comment by rbeede** [comment]
Attempting to rotate the display in settings resulted in just a blank screen. Boot time is much longer than OEM OS.

**Comment by devinsmith** [comment]
I am using void-live-x86_64-20191109.iso daily on my RCA Cambio. I'm not sure if it's the exact same model that you have. The DMI dmesg reports: RCA W101 V2 TH2/WT9303W004, BIOS 5.6.5 09/23/2016
